name: Update Engine

on:
  workflow_dispatch:

jobs:
  update:
    name: Update engine cli in include

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Remove old version
        run: |
          rm -rf ./src/include/gly-engine/cli.lua
          rm -rf ./src/include/gly-engine/bundler/bundler_cli.lua
          rm -rf ./src/include/gly-engine/bundler/bundler.lua

      - name: Download new version
        run: |
          curl get.gamely.com.br/cli.lua -o ./src/include/gly-engine/cli.lua
          curl get.gamely.com.br/bundler_cli.lua -o ./src/include/gly-engine/bundler_cli.lua
          curl get.gamely.com.br/bundler.lua -o ./src/include/gly-engine/bundler.lua

      - name: Commit files
        run: |
          git config --local user.name "gamelly-bot"
          git add .
          git commit -m "chore: updating gly engine CLI"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
